import org.example.JosephusProblem;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        int n;
        int k;
        if (args.length > 0) {
            try {
                n = Integer.parseInt(args[0]);
                k = Integer.parseInt(args[1]);
                int result = JosephusProblem.josephus(n,k);
                System.out.printf("JosephusProblem(%d,%d) = %d",n,k,result);
            } catch (Exception e) {
                System.err.println(e);
                System.exit(1);
            }
        }
    }
}
