/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        int firstArg;
        int secondArg;
        if (args.length > 0) {
            try {
                firstArg = Integer.parseInt(args[0]);
                secondArg = Integer.parseInt(args[1]);
            } catch (Exception e) {
                System.err.println(e);
                System.exit(1);
            }
        }
    }
}
